import { Inter } from "next/font/google";
import "./globals.css";
import BaseLayout from "@/components/shared/BaseLayout";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todo List App",
  description:
    "Generated by create next app with Ant Design. Author: Md. Moniruzzaman Bappy",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BaseLayout>{children}</BaseLayout>
        <Toaster
          toastOptions={{ duration: 3000 }}
          containerClassName="print:hidden"
        />
      </body>
    </html>
  );
}
